language: python
python:
  - 3.7
install:
  - pip install --upgrade setuptools pip
  - pip install jupyter-repo2docker
  - pip freeze
script:
  - jupyter-repo2docker https://github.com/binder-examples/requirements date
