os: osx
osx_image: xcode6.4
language: generic
before_install:
  - |
    # Remove homebrew.
    echo "Removing homebrew from Travis CI to avoid conflicts."
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
    chmod +x ~/uninstall_homebrew
    ~/uninstall_homebrew -fq
    rm ~/uninstall_homebrew
install:
  - set -e
  - find /Applications -name '*.sdk'
  - |
    # Install Miniconda.
    echo "Installing a fresh version of Miniconda."
    MINICONDA_URL="https://repo.continuum.io/miniconda"
    MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
    curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    bash $MINICONDA_FILE -b

  - |
    # Configure conda.
    echo "Configuring conda."
    source /Users/travis/miniconda3/bin/activate root
    conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
    source run_conda_forge_build_setup
    conda config --add channels conda-forge

script:
  - conda create -y -c minrk -n openmpi openmpi toolchain
  - conda activate openmpi
  - conda list
  - |
    export OMPI_MCA_plm=isolated
    export OMPI_MCA_btl_vader_single_copy_mechanism=none
    export OMPI_MCA_rmaps_base_oversubscribe=yes
  - env | sort
  - mpicxx test.cxx -o test
  - mpiexec -n 4 ./test
