on:
  push:
    branches:
      - actions

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove libzmq5 || true # workaround https://github.com/actions/virtual-environments/issues/3317
          sudo apt-get -y install libzmq3-dev libsodium-dev
