on:
  push:
    branches:
      - actions

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: install linux dependencies
        run: |
          sudo apt-get -f install
          sudo apt-get update
          sudo apt-get -y install libzmq3-dev libsodium-dev
