on:
  push:
    branches:
      - actions

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/condaforge/linux-anvil-x86_64:alma9
      env:
        MAMBA_ROOT_PREFIX: /opt/conda
    timeout-minutes: 10
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - run: |
          mamba create -n mpi4py --override-channels -c conda-forge/linux-aarch64 -c conda-forge/noarch mpi4py
      - run: |
          mamba run -a '' -n mpi4py mpiexec -n 2 python -m mpi4py.bench helloworld
