on:
  push:
    branches:
      - actions

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up QEMU
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
          ls /proc/sys/fs/binfmt_misc/
      - run: |
          cat <<EOF | docker run --rm -e MAMBA_ROOT_PREFIX=/opt/conda -i quay.io/condaforge/linux-anvil-x86_64:alma9
          mv ~/.cache ~/dotcache
          eval $(mamba shell hook)
          mamba create -y -n mpi4py --override-channels -c conda-forge/linux-aarch64 -c conda-forge/noarch mpi4py openmpi python=3.12 sysroot_linux-aarch64
          mamba activate mpi4py
          echo $CONDA_PREFIX
          export QEMU_LD_PREFIX=$CONDA_PREFIX/aarch64-conda-linux-gnu/sysroot
          qemu-aarch64-static mpiexec -n 2 python -m mpi4py.bench helloworld
          EOF
